version: '3'

services:

  irc:
    image: "yrpri/ngircd"
    networks:
      - helga
    ports:
      - "6667:6667"

  mongo:
    image: "mongo:3.4"
    networks:
      - helga
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  helga:
    build: .
    image: bigjust/helga
    command: helga --settings=docker/dev-settings.py
    volumes:
      - .:/code
    networks:
      - helga
    depends_on:
      - mongo
      - irc

networks:
  helga:
    driver: bridge

volumes:
  mongo_data:
