services:

  irc:
    image: inspircd/inspircd-docker:latest
    ports:
      - 6667:6667

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  helga:
    build: .
    environment:
      - HELGA_IRC_SERVER=irc
      - HELGA_MONGO_HOST=mongo
    volumes:
      - .:/code
    depends_on:
      - mongo
      - irc

volumes:
  mongo_data:

# Made with Bob
